language: python
python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
services:
  - redis-server
install:
  - pip install -e .
  - pip install coveralls pytest-cov==1.6

script: py.test --cov . --cov-config .coveragerc

after_success:
  coveralls
